### PR TITLE
Es5 builds

### PR DESCRIPTION
**Pull request by gprzybylowicz**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Holy cow!

**Comment by gprzybylowicz** [comment]
Yeah, I know it's quite a lot of changes :) Just to sum up here:
1) I copied rollup config and added typescript instead of surcase
2) Needed to turn off declaration in config by default cause rollup throws errors, same with lack of 'baseUrl'
3) Declarations set to true in tsconfig-api.json
4) New ver of rollup

**Comment by ivanpopelyshev** [comment]
Yes, i thought to do something like that.

OK, i'll check tomorrow :)

**Comment by gprzybylowicz** [comment]
Hi @ivanpopelyshev Did you have chance to review PR?

**Comment by ivanpopelyshev** [comment]
done, please check it

**Comment by gprzybylowicz** [comment]
thanks,  works like a charm

**Pull request merged**
