### PR TITLE
fix NBSP issues

### PR DESCRIPTION
**Pull request by konan21**
Hello, I had an issue with NBSP in our project when we use source-map-loader.
image

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
oh right, i made PR in https://github.com/EsotericSoftware/spine-runtimes/pull/1923 , but forgot to fix it in my repo

**Comment by ivanpopelyshev** [comment]
done, please check it

**Comment by konan21** [comment]
Now have following error:
`WARNING in ./node_modules/@pixi-spine/runtime-4.0/lib/runtime-4.0.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'node_modules\@pixi-spine\runtime-4.0\src\core\attachments\RegionAt
tachment.ts' file: Error: ENOENT: no such file or directory, open 'node_modules\@pixi-spine\runtime
-4.0\src\core\attachments\RegionAttachment.ts'
`
which is strange, because when I removed manually those `&nbsp;` source maps were parsed properly

**Comment by ivanpopelyshev** [comment]
I also switched build to es5 result, sourcemaps might differ too.

**Comment by ivanpopelyshev** [comment]
I cloned `pixi-spine` in bare repo, checked for alt+0160 symbols in my IDE - its clean

**Comment by ivanpopelyshev** [comment]
Can you give me minimal setup to experience this error?

**Comment by konan21** [comment]
sure, here you are
https://github.com/konan21/new_blank_pixijs_app

thanks for your help

**Comment by konan21** [comment]
try to build and you will see the errors

**Comment by ivanpopelyshev** [comment]
I see it. Basically, source maps dont include sources , and that's why it all goes bad. If we used something like Maven, sources could be in separate artifact , but in npm i have to include sources anyway, right? 

OK, how do I put sources in the sourcemap with my current rollup set up?

**Comment by konan21** [comment]
now you switched target build to es5, right?
but what was before?

**Comment by ivanpopelyshev** [comment]
his PR: https://github.com/pixijs/spine/pull/397

You can try to roll back pixi-spine 3.0.5 version and see if `node_modules/@pixi-spine/runtime***` contain map files with actual code and not just references?

**Comment by konan21** [comment]
hmm, now the same error with 3.0.5 :|

**Comment by ivanpopelyshev** [comment]
ok, so now you have to go through configs and find out how to make correct mappings with this rollup+terser combination :)

**Comment by ivanpopelyshev** [comment]
@konan21 
hey, can you try `3.0.8` ?

**Comment by konan21** [comment]
@ivanpopelyshev 
hello, works like a charm :)

**Comment by konan21** [comment]
It's not related to the pixi-spine. I also update pixi.js and pixi-particles to the latest version and now have a strange error
image

**Comment by ivanpopelyshev** [comment]
It turned out, i had to remove `declarations:true` from tsconfig because it was conflicting with whatever rollup ts plugin was doing :)

oh, pixi-parrticles.. you read that thing about 6.1.0 particles renamed?

**Comment by konan21** [comment]
Nope, what was renamed in 6.1.0 version?
Where I can read about this?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixijs/releases/tag/v6.1.0

pixi-particles for v6 is `@pixi/particles`, but you can use it only with `6.1`, because previous versions used same name for what is `@pixi/particle-container` now, the thing that hosts `ParticleContainer`

**Comment by konan21** [comment]
so `@pixi/particles` is deprecated now
then if you wish to use latest version of `pixi.js` with latest version of `pixi-particles` you will have `@pixi/particle-container` (which is automatically instaled by `pixi-particles`)

But I use all latest versions 
`"dependencies": {
        "@pixi/sound": "^4.0.4",
        "pixi-particles": "^4.3.1",
        "pixi-spine": "^3.0.8",
        "pixi.js": "^6.1.1"
    }`
is this means that I should have an error?

**Comment by ivanpopelyshev** [comment]
its not deprecated , its actually "@pixi/particle-emitter" right now : https://github.com/pixijs/pixi-particles/blob/1ade581cceb897bfd86c8d3430b8eea80765f5d9/package.json#L2

I honestly dont understand what is going on anymore

**Comment by konan21** [comment]
Okay, but the problem is that `Class 'Container' defines instance member property 'renderCanvas', but extended class 'LinkedListContainer' defines it as instance member function.`
And that issue appeared in `pixi-particles/index.d.ts:854:2 `
And it's not about [ParticleContainer Package Renamed ](https://github.com/pixijs/pixijs/releases/tag/v6.1.0)

Should I create an issue in [pixi-particles](https://github.com/pixijs/pixi-particles/issues)?

**Comment by ivanpopelyshev** [comment]
Yes, and if you make minimal setup, that'll be handled fast. Also reference this discussion. Im not contributor of pixi-particles but i can test stuff :)

**Comment by konan21** [comment]
Hello again :)
Here is an issue  https://github.com/pixijs/pixi-particles/issues/160

**Pull request merged**
